import { readFileSync } from "node:fs";
import path from "node:path";
import { render } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { parseCssVars } from "@/lib/a11y/contrast";
import {
  CAPSULE_PILL_PATH,
  CAPSULE_PLANT_PATH,
  CAPSULE_VIEWBOX,
  CapsuleIcon,
} from "@/components/brand/capsule-icon";

const fills = (svg: SVGSVGElement) =>
  [...svg.querySelectorAll("path")].map((path) => path.getAttribute("fill"));

describe("CapsuleIcon", () => {
  // Generated by /ship coverage audit
  // Value: protects=every colour capsule paints from its own gradients, so several on one page (persona grid, approach list) never borrow or lose each other's fill;
  //   fails_when=gradient ids stop being per-instance (useId dropped or the prefix collapses), or a path references a gradient id that is not defined in its own svg;
  //   why_new=CapsuleIcon is new and untested, and duplicate SVG ids fail silently in the browser; seam=none
  it("gives each colour icon its own gradients and points both halves at them", () => {
    const { container } = render(
      <>
        <CapsuleIcon />
        <CapsuleIcon tone="reversed" />
      </>,
    );
    const svgs = [...container.querySelectorAll("svg")];
    const ids = svgs.flatMap((svg) => [...svg.querySelectorAll("linearGradient")].map((g) => g.id));
    expect(ids).toHaveLength(4);
    expect(new Set(ids).size).toBe(4);
    for (const svg of svgs) {
      const own = [...svg.querySelectorAll("linearGradient")].map((g) => `url(#${g.id})`);
      expect(fills(svg)).toEqual(own);
    }
    const firstStop = (svg: SVGSVGElement) =>
      svg.querySelector("linearGradient stop")?.getAttribute("stop-color");
    // The reversed colourway is a different set of stops for Night grounds, not the same art.
    expect(firstStop(svgs[0]!)).not.toBe(firstStop(svgs[1]!));
  });

  // Generated by /ship coverage audit
  // Value: protects=the mono capsule follows the text colour, so it inverts with the demo rail's current-page row and the access page hover;
  //   fails_when=mono emits gradients or a fixed fill instead of inheriting currentColor;
  //   why_new=the mono tone replaced LeafIcon gradient={false} in the rail and access page with no test; seam=none
  it("draws the mono tone in currentColor with no gradients", () => {
    const { container } = render(<CapsuleIcon tone="mono" />);
    const svg = container.querySelector("svg")!;
    expect(svg.querySelector("defs")).toBeNull();
    expect(svg.querySelector("g")).toHaveAttribute("fill", "currentColor");
    expect(fills(svg)).toEqual([null, null]);
  });

  // Generated by /ship coverage audit
  // Value: protects=the capsule is decorative by default and becomes a named image only when given a title;
  //   fails_when=the untitled icon is exposed to assistive tech or a titled one loses role img;
  //   why_new=CapsuleIcon is new and untested; seam=none
  it("is hidden from assistive tech unless it has a title", () => {
    const { container, rerender } = render(<CapsuleIcon />);
    const svg = () => container.querySelector("svg")!;
    expect(svg()).toHaveAttribute("aria-hidden", "true");
    expect(svg()).not.toHaveAttribute("role");
    rerender(<CapsuleIcon title="NEWMA" />);
    expect(svg()).not.toHaveAttribute("aria-hidden");
    expect(svg()).toHaveAttribute("role", "img");
    expect(svg().querySelector("title")).toHaveTextContent("NEWMA");
  });

  // Value: protects=the colour capsule paints in the current brand tokens (Lime to Emerald, Deep Teal to Teal), so a palette retune cannot leave every capsule icon on the old colours; fails_when=color.css changes leaf/leaf-bright/capsule/capsule-deep without the icon following; why_new=the icon hardcodes its stops and no test tied them to the tokens; seam=none
  it("paints the colour tone from the brand colour tokens", () => {
    const vars = parseCssVars(
      readFileSync(path.resolve(__dirname, "../../../src/styles/tokens/color.css"), "utf8"),
    );
    const { container } = render(<CapsuleIcon />);
    const stops = [...container.querySelectorAll("linearGradient")].map((gradient) =>
      [...gradient.querySelectorAll("stop")].map((stop) => stop.getAttribute("stop-color")),
    );
    expect(stops).toEqual([
      [vars["--color-leaf-bright"], vars["--color-leaf"]],
      [vars["--color-capsule-deep"], vars["--color-capsule"]],
    ]);
  });

  // Generated by /ship pre-landing review
  // Value: protects=the list bullet mask (public/brand/capsule-bullet.svg) draws the same capsule as CapsuleIcon: same viewBox, seam and halves;
  //   fails_when=the icon's geometry is retuned in one place only, so .leaf-list bullets drift from the capsules beside them;
  //   why_new=the bullet copies the icon's geometry by hand and nothing tied the two together; seam=none
  it("matches the list bullet mask's geometry", () => {
    const bullet = readFileSync(
      path.join(process.cwd(), "public/brand/capsule-bullet.svg"),
      "utf8",
    );
    expect(bullet).toContain(`viewBox="${CAPSULE_VIEWBOX}"`);
    expect(bullet).toContain(`d="${CAPSULE_PLANT_PATH}"`);
    expect(bullet).toContain(`d="${CAPSULE_PILL_PATH}"`);
    expect(bullet).toContain('transform="rotate(-45)"');
  });

  // Generated by /ship pre-landing review
  // Value: protects=the colour capsule paints the brand tokens: the plant half Lime to Emerald, the pill half Deep Teal to Teal;
  //   fails_when=the palette in color.css changes and the icon's hard-coded stops do not follow (or the halves swap), so icons drift from the rest of the brand;
  //   why_new=brand.test syncs BRAND_HEX with color.css, but nothing tied CapsuleIcon's gradient stops to the tokens; seam=none
  it("paints the colour capsule from the brand tokens", () => {
    const tokens = parseCssVars(
      readFileSync(path.join(process.cwd(), "src/styles/tokens/color.css"), "utf8"),
    );
    const { container } = render(<CapsuleIcon />);
    const stops = (half: string) =>
      [...container.querySelectorAll(`linearGradient[id$="-${half}"] stop`)].map((stop) =>
        stop.getAttribute("stop-color")?.toLowerCase(),
      );
    expect(stops("plant")).toEqual([tokens["--color-leaf-bright"], tokens["--color-leaf"]]);
    expect(stops("pill")).toEqual([tokens["--color-capsule-deep"], tokens["--color-capsule"]]);
  });
});
