import { gotoHeroReady } from "../support/hero";
import { expect, test } from "../support/test";

// Value: protects=the mobile section menu is really closed until Menu is pressed, opens with tappable links, and closes when one is chosen; fails_when=the hidden attribute stops hiding the list under the page's CSS, aria-expanded drifts, or a link is smaller than 44 px; why_new=the unit test runs without any CSS and no e2e pressed Menu, so a flex class overriding hidden would pass; seam=none
test("the mobile section menu opens on Menu and closes when a link is chosen", async ({
  page,
  isMobile,
}) => {
  test.skip(!isMobile, "the Menu button only shows below the md breakpoint");
  // The Menu button is server-rendered and only works once hydrated: wait for the page's ready hook.
  await gotoHeroReady(page);
  const menu = page.getByRole("button", { name: "Menu" });
  const list = page.locator("#mobile-sections");

  await expect(menu).toHaveAttribute("aria-expanded", "false");
  await expect(list).toBeHidden();

  await menu.click();
  await expect(menu).toHaveAttribute("aria-expanded", "true");
  await expect(list).toBeVisible();
  const links = list.getByRole("link");
  expect(await links.count()).toBeGreaterThan(0);
  const box = await links.first().boundingBox();
  expect(box?.height ?? 0).toBeGreaterThanOrEqual(44);

  await links.first().click();
  await expect(list).toBeHidden();
});

// Generated by /ship pre-landing review
// Value: protects=a section chosen from the mobile menu lands just below the sticky header, like any in-page anchor;
//   fails_when=the closing sheet stays in flow during the anchor scroll, so the section ends up the sheet's height past the header (QA run 3: -103 px vs 110 px);
//   why_new=the test above only checks that the sheet closes, never where the page lands; seam=none
test("a section chosen from the mobile menu lands below the header", async ({ page, isMobile }) => {
  test.skip(!isMobile, "the Menu button only shows below the md breakpoint");
  await gotoHeroReady(page);
  await page.getByRole("button", { name: "Menu" }).click();
  await page.locator("#mobile-sections").getByRole("link", { name: "How it works" }).click();
  await expect(page).toHaveURL(/#workflow$/);
  // The page scrolls smoothly: measure once the scroll position has held still for a few frames.
  const gap = await page.evaluate(async () => {
    const frame = () => new Promise<void>((resolve) => requestAnimationFrame(() => resolve()));
    let last = Number.NaN;
    for (let still = 0, tries = 0; still < 5 && tries < 600; tries += 1) {
      await frame();
      still = window.scrollY === last ? still + 1 : 0;
      last = window.scrollY;
    }
    const header = document.querySelector("[data-site-header]")!.getBoundingClientRect();
    return Math.round(
      document.getElementById("workflow")!.getBoundingClientRect().top - header.bottom,
    );
  });
  expect(gap).toBeGreaterThanOrEqual(-1);
  expect(gap).toBeLessThanOrEqual(24);
});
