import { describe, expect, it } from "vitest";
import manifest from "@/app/manifest";
import { BRAND_HEX } from "@/lib/brand";

describe("web app manifest", () => {
  it("is installable with maskable icons and app shortcuts", () => {
    const data = manifest();
    expect(data.display).toBe("standalone");
    expect(data.start_url).toBe("/");
    expect(data.icons?.some((icon) => icon.purpose === "maskable")).toBe(true);
    expect(data.icons?.some((icon) => icon.sizes === "512x512")).toBe(true);
    expect(data.shortcuts?.map((item) => item.url)).toEqual(["/access", "/#components"]);
  });

  // Generated by /ship coverage audit
  // Value: protects=the installed app is titled with the full brand name, keeps the short NEWMA label under its icon, and tints the title bar Night to match the dark viewport theme colour;
  //   fails_when=theme_color reverts to the accent or any other hex, or name/short_name change so the home-screen label or install dialog title drifts;
  //   why_new=the manifest test only checked installability, never the brand fields; seam=none
  it("names and tints the installed app with the brand", () => {
    const data = manifest();
    expect(data.name).toBe("NEWMA by LivFul Therapeutics");
    expect(data.short_name).toBe("NEWMA");
    expect(data.theme_color).toBe(BRAND_HEX.night);
  });
});
