import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { brandLogoSrc } from "@/lib/seo/brand-logo";

const PREFIX = "data:image/svg+xml;base64,";
const SAFE_SVG_ELEMENTS = new Set([
  "svg",
  "g",
  "defs",
  "path",
  "rect",
  "circle",
  "ellipse",
  "polygon",
  "linearGradient",
  "radialGradient",
  "stop",
  "title",
]);

describe("brandLogoSrc", () => {
  // Generated by /ship coverage audit
  // Value: protects=Open Graph cards inline the brand lockup as a valid SVG data URI read from a file that ships in public/brand;
  //   fails_when=the path points at a deleted or renamed file (readFileSync throws during the OG build) or the MIME type no longer matches the bytes, so satori draws a broken image;
  //   why_new=nothing called brandLogoSrc in a test, and the switch from logo-horizontal.png to newma-logo.svg changed both path and MIME; seam=none
  it("inlines the shipped SVG lockup as an svg+xml data URI", () => {
    const src = brandLogoSrc();

    expect(src.startsWith(PREFIX)).toBe(true);
    const markup = Buffer.from(src.slice(PREFIX.length), "base64").toString("utf8");
    expect(markup.trimStart()).toMatch(/^(<\?xml[^>]*>\s*)?<svg[\s>]/);
    expect(markup.trimEnd()).toMatch(/<\/svg>$/);
    expect(markup).toBe(
      readFileSync(path.join(process.cwd(), "public/brand/newma-logo.svg"), "utf8"),
    );
  });

  // Value: protects=the OG lockup keeps to SVG features satori/resvg draw reliably, so every social card shows the logo;
  //   fails_when=a brand-pack refresh brings in <text> (no font in resvg), <style>, <image>, <use>, filters, masks or clip paths, which render blank or wrong on the card while the data-URI test above still passes;
  //   why_new=nothing checked what the logo is made of, only that its bytes are inlined; the rendered card was checked by eye once; seam=none
  it("draws the lockup only from shapes and gradients the OG renderer supports", () => {
    const markup = readFileSync(path.join(process.cwd(), "public/brand/newma-logo.svg"), "utf8");
    const elements = new Set(Array.from(markup.matchAll(/<([a-zA-Z]+)/g), (match) => match[1]));

    expect([...elements].filter((name) => !SAFE_SVG_ELEMENTS.has(name!))).toEqual([]);
    expect(markup).not.toMatch(/\b(?:href|xlink:href)=/);
  });
});
