import type { Page } from "@playwright/test";
import { afterEach, describe, expect, it } from "vitest";
import { sequentialKey } from "../../support/keyboard";

const pageOn = (engine: string | null) =>
  ({
    context: () => ({
      browser: () => (engine === null ? null : { browserType: () => ({ name: () => engine }) }),
    }),
  }) as unknown as Page;

const realPlatform = process.platform;
const onPlatform = (platform: NodeJS.Platform) =>
  Object.defineProperty(process, "platform", { configurable: true, value: platform });

describe("sequentialKey", () => {
  afterEach(() => onPlatform(realPlatform));

  // Generated by /ship coverage audit
  // Value: protects=keyboard e2e walks reach links in every engine: macOS WebKit gets Alt+Tab (its Tab skips links), while Linux WebKit in CI and Chromium/Firefox keep the plain key;
  //   fails_when=the platform check is dropped (CI's Linux WebKit presses Alt+Tab), the engine check is dropped (Chromium on a Mac presses Alt+Tab), Shift+Tab loses its Alt, or a persistent-context page without a browser throws;
  //   why_new=the helper is new and only exercised by e2e specs on whichever single platform runs them; seam=none
  it("adds Alt only for WebKit on macOS", () => {
    onPlatform("darwin");
    expect(sequentialKey(pageOn("webkit"), "Tab")).toBe("Alt+Tab");
    expect(sequentialKey(pageOn("webkit"), "Shift+Tab")).toBe("Alt+Shift+Tab");
    expect(sequentialKey(pageOn("chromium"), "Tab")).toBe("Tab");
    expect(sequentialKey(pageOn("firefox"), "Shift+Tab")).toBe("Shift+Tab");
    expect(sequentialKey(pageOn(null), "Tab")).toBe("Tab");
    onPlatform("linux");
    expect(sequentialKey(pageOn("webkit"), "Tab")).toBe("Tab");
    expect(sequentialKey(pageOn("webkit"), "Shift+Tab")).toBe("Shift+Tab");
  });
});
