#!/usr/bin/env node
// Contract check (IP §5.6): verify the pinned spec hash, regenerate the typed client, fail on drift.
// Usage: node scripts/api-check.mjs [--update] [--no-typecheck]
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

export const LOCK_PATH = "api/openapi.lock";
export const OUT_PATH = "src/lib/api/generated/schema.d.ts";
const SHA_PREVIEW_LENGTH = 12;

export class ApiCheckError extends Error {}

const fail = (message) => {
  throw new ApiCheckError(message);
};

export async function loadSpec(source, repoRoot, fetchImpl = fetch) {
  if (/^https?:\/\//.test(source)) {
    const res = await fetchImpl(source);
    if (!res.ok) fail(`fetch ${source} -> ${res.status}`);
    return await res.text();
  }
  const specPath = path.resolve(repoRoot, source);
  if (!existsSync(specPath)) fail(`spec not found at ${specPath}`);
  return readFileSync(specPath, "utf8");
}

export const sha256 = (text) => createHash("sha256").update(text).digest("hex");

// Same-line whitespace only: a schema property named `version` (value on the next line) must not match.
export const specVersion = (spec) =>
  spec.match(/^[ \t]*version:[ \t]*['"]?([^'"\n]+?)['"]?[ \t]*$/m)?.[1].trim();

export async function generateClient(spec, lock) {
  const header = `// GENERATED by scripts/api-check.mjs from ${lock.source} (api-v${lock.version}). Do not edit.\n`;
  return header + astToString(await openapiTS(spec));
}

function verifyLock({ lock, lockPath, sha, spec, update }) {
  if (update) {
    writeFileSync(lockPath, JSON.stringify({ ...lock, sha256: sha }, null, 2) + "\n");
  } else if (sha !== lock.sha256) {
    fail(
      `sha256 mismatch for ${lock.source}: lock ${lock.sha256} vs spec ${sha}. ` +
        "Run pnpm api:update after reviewing the contract change.",
    );
  }
  const version = specVersion(spec);
  if (version !== lock.version) fail(`spec version ${version} != lock version ${lock.version}`);
}

function typecheck(cwd) {
  try {
    execFileSync("pnpm", ["exec", "tsc", "--noEmit"], { cwd, stdio: "inherit" });
  } catch {
    fail("typecheck failed against the regenerated client");
  }
}

export async function runApiCheck({
  cwd = process.cwd(),
  repoRoot = process.env.API_CHECK_REPO_ROOT ?? cwd,
  args = new Set(),
  fetchImpl = fetch,
} = {}) {
  const update = args.has("--update");
  const lockPath = path.join(cwd, LOCK_PATH);
  const lock = JSON.parse(readFileSync(lockPath, "utf8"));
  const spec = await loadSpec(lock.source, repoRoot, fetchImpl);
  const sha = sha256(spec);
  verifyLock({ lock, lockPath, sha, spec, update });

  writeFileSync(path.join(cwd, OUT_PATH), await generateClient(spec, lock));
  const diff = execFileSync("git", ["status", "--porcelain", "--", OUT_PATH], {
    cwd,
    encoding: "utf8",
  });
  if (diff.trim() && !update) {
    fail("generated client is stale; run pnpm api:update and commit src/lib/api/generated");
  }
  if (!args.has("--no-typecheck")) typecheck(cwd);
  return `api:check: ok (api-v${lock.version}, sha256 ${sha.slice(0, SHA_PREVIEW_LENGTH)}…)`;
}

async function main() {
  try {
    const summary = await runApiCheck({ args: new Set(process.argv.slice(2)) });
    process.stdout.write(`${summary}\n`);
  } catch (error) {
    if (!(error instanceof ApiCheckError)) throw error;
    process.stderr.write(`api:check: ${error.message}\n`);
    process.exit(1);
  }
}

const isDirectRun = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isDirectRun) await main();
