#!/usr/bin/env node
// Contract check (IP §5.6): verify the pinned spec hash, regenerate the typed client, fail on drift.
// Usage: node scripts/api-check.mjs [--update] [--no-typecheck]
// API_CHECK_SPEC_SOURCE overrides where the spec is fetched from (CI points it at the deployed
// API's /openapi.yaml); the lock's pinned version and sha256 are still enforced against it.
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import { parse as parseYaml } from "yaml";

export const LOCK_PATH = "api/openapi.lock";
export const OUT_PATH = "src/lib/api/generated/schema.d.ts";
const SHA_PREVIEW_LENGTH = 12;
const FETCH_TIMEOUT_MS = 15_000;

export class ApiCheckError extends Error {}

const fail = (message) => {
  throw new ApiCheckError(message);
};

export async function loadSpec(source, repoRoot, fetchImpl = fetch) {
  if (/^https?:\/\//.test(source)) {
    const res = await fetchImpl(source, { signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) });
    if (!res.ok) fail(`fetch ${source} -> ${res.status}`);
    return await res.text();
  }
  const specPath = path.resolve(repoRoot, source);
  if (!existsSync(specPath)) fail(`spec not found at ${specPath}`);
  return readFileSync(specPath, "utf8");
}

export const sha256 = (text) => createHash("sha256").update(text).digest("hex");

/** Parse the OpenAPI document and return `info.version`; malformed input is a contract failure. */
export function specVersion(spec) {
  let doc;
  try {
    doc = parseYaml(spec);
  } catch (error) {
    fail(`spec is not valid YAML: ${error.message}`);
  }
  const version = doc?.info?.version;
  if (typeof version !== "string" || version.length === 0) fail("spec has no info.version string");
  return version;
}

export async function generateClient(spec, lock) {
  const header = `// GENERATED by scripts/api-check.mjs from ${lock.source} (api-v${lock.version}). Do not edit.\n`;
  return header + astToString(await openapiTS(spec));
}

/** In --update mode the validated spec rewrites the lock; otherwise the lock must match it. */
function resolveLock({ lock, lockPath, source, sha, version, update }) {
  if (update) {
    const next = { ...lock, version, sha256: sha };
    writeFileSync(lockPath, JSON.stringify(next, null, 2) + "\n");
    return next;
  }
  if (sha !== lock.sha256) {
    fail(
      `sha256 mismatch for ${source}: lock ${lock.sha256} vs spec ${sha}. ` +
        "Run pnpm api:update after reviewing the contract change.",
    );
  }
  if (version !== lock.version) fail(`spec version ${version} != lock version ${lock.version}`);
  return lock;
}

function generatedDiff(cwd) {
  try {
    return execFileSync("git", ["status", "--porcelain", "--", OUT_PATH], {
      cwd,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
  } catch {
    return fail(`${cwd} is not a git repository (git status failed); run from the repo root`);
  }
}

function typecheck(cwd) {
  try {
    execFileSync("pnpm", ["exec", "tsc", "--noEmit"], { cwd, stdio: "inherit" });
  } catch {
    fail("typecheck failed against the regenerated client");
  }
}

export async function runApiCheck({
  cwd = process.cwd(),
  repoRoot = process.env.API_CHECK_REPO_ROOT ?? cwd,
  args = new Set(),
  fetchImpl = fetch,
  env = process.env,
} = {}) {
  const update = args.has("--update");
  const lockPath = path.join(cwd, LOCK_PATH);
  const lock = JSON.parse(readFileSync(lockPath, "utf8"));
  const source = env.API_CHECK_SPEC_SOURCE || lock.source;
  const spec = await loadSpec(source, repoRoot, fetchImpl);
  const version = specVersion(spec);
  const sha = sha256(spec);
  const resolved = resolveLock({ lock, lockPath, source, sha, version, update });

  writeFileSync(path.join(cwd, OUT_PATH), await generateClient(spec, resolved));
  if (generatedDiff(cwd).trim() && !update) {
    fail("generated client is stale; run pnpm api:update and commit src/lib/api/generated");
  }
  if (!args.has("--no-typecheck")) typecheck(cwd);
  return `api:check: ok (api-v${resolved.version}, sha256 ${sha.slice(0, SHA_PREVIEW_LENGTH)}…)`;
}

async function main() {
  try {
    const summary = await runApiCheck({ args: new Set(process.argv.slice(2)) });
    process.stdout.write(`${summary}\n`);
  } catch (error) {
    if (!(error instanceof ApiCheckError)) throw error;
    process.stderr.write(`api:check: ${error.message}\n`);
    process.exit(1);
  }
}

const isDirectRun = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isDirectRun) await main();
