import { readFileSync } from "node:fs";
import path from "node:path";
import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { Wordmark } from "@/components/site/wordmark";
import { cssBlockAfter } from "../../support/css-block";

// next/image may route the file through its optimizer, so the brand path is read from the decoded src.
const artOf = (img: Element): string => {
  const src = decodeURIComponent(img.getAttribute("src") ?? "");
  return /\/brand\/[a-z-]+\.svg/.exec(src)?.[0] ?? src;
};

describe("Wordmark", () => {
  // Generated by /ship coverage audit
  // Value: protects=each lockup and ground gets its own brand-pack file (wordmark vs logo, primary vs reversed), never one file recoloured;
  //   fails_when=the lockup or tone prop is ignored, the LOCKUPS table points a colourway at the wrong file, or the footer's dark logo falls back to the light one;
  //   why_new=no test read the Wordmark's image source, so the footer on Night could ship the dark-ink logo unnoticed; seam=none
  it("picks the file for the requested lockup and colourway", () => {
    const cases = [
      [{}, "/brand/newma-wordmark.svg"],
      [{ tone: "dark" as const }, "/brand/newma-wordmark-reversed.svg"],
      [{ lockup: "logo" as const }, "/brand/newma-logo.svg"],
      [{ lockup: "logo" as const, tone: "dark" as const }, "/brand/newma-logo-reversed.svg"],
    ] as const;
    for (const [props, file] of cases) {
      const { container, unmount } = render(<Wordmark {...props} />);
      const images = container.querySelectorAll("img");
      expect(images, file).toHaveLength(1);
      expect(artOf(images[0]!), JSON.stringify(props)).toBe(file);
      unmount();
    }
  });

  // Generated by /ship coverage audit
  // Value: protects=the adaptive header lockup ships both colourways, hooked to the CSS that swaps them on [data-tone], with the light one as the priority image and the hidden dark one preloaded at low priority so the first dark swap is never blank;
  //   fails_when=a colourway is dropped, the wordmark-light/wordmark-dark hooks are renamed away from the globals.css selectors, the dark one goes lazy again (a lazy image under display:none is not fetched until shown), or both images are prioritised;
  //   why_new=the header tone probe was untested end to end and nothing checked the wordmark half of the swap; seam=none
  it("renders both colourways for the adaptive tone, light prioritised and dark preloaded at low priority", () => {
    const { container } = render(<Wordmark tone="adaptive" priority />);
    const link = screen.getByRole("link", { name: "NEWMA by LivFul Therapeutics" });
    const light = container.querySelector("img.wordmark-light");
    const dark = container.querySelector("img.wordmark-dark");
    expect(link).toContainElement(light as HTMLElement);
    expect(link).toContainElement(dark as HTMLElement);
    expect(artOf(light!)).toBe("/brand/newma-wordmark.svg");
    expect(artOf(dark!)).toBe("/brand/newma-wordmark-reversed.svg");
    // Both images are decorative; the link carries the name.
    expect(light).toHaveAttribute("alt", "");
    expect(dark).toHaveAttribute("alt", "");
    expect(light).not.toHaveAttribute("loading", "lazy");
    expect(light).not.toHaveAttribute("fetchpriority", "low");
    expect(dark).toHaveAttribute("loading", "eager");
    expect(dark).toHaveAttribute("fetchpriority", "low");
  });

  // Value: protects=mobile LCP: a below-the-fold adaptive lockup (the footer logo) fetches neither colourway before first paint, where Lighthouse's simulation charges every early request to LCP;
  //   fails_when=the standby colourway is made eager without priority again;
  //   why_new=the footer became adaptive, and its eager standby added a reversed logo to the requests before LCP; seam=none
  it("keeps both colourways lazy when the lockup is not a priority image", () => {
    const { container } = render(<Wordmark lockup="logo" tone="adaptive" />);
    for (const img of container.querySelectorAll("img")) {
      expect(img).toHaveAttribute("loading", "lazy");
      expect(img).not.toHaveAttribute("fetchpriority");
    }
  });

  // Value: protects=the adaptive header shows exactly one colourway: light by default, reversed only on screen over a dark tone, never under forced colours or print; fails_when=the globals.css swap rules are deleted, renamed away from the wordmark-light/wordmark-dark hooks, or escape the screen-and-no-forced-colours guard; why_new=the class-name test above never reads the CSS that acts on those classes; seam=none
  it("is swapped by globals.css only on screen and outside forced colours", () => {
    const css = readFileSync(path.resolve(__dirname, "../../../src/app/globals.css"), "utf8");
    expect(css).toMatch(/\n\.wordmark-dark\s*\{\s*display:\s*none;/);
    const guarded = cssBlockAfter(css, "@media screen and (forced-colors: none)");
    expect(guarded).toMatch(/\[data-tone="dark"\] \.wordmark-light[\s\S]*?display:\s*none;/);
    expect(guarded).toMatch(/\[data-tone="dark"\] \.wordmark-dark[\s\S]*?display:\s*block;/);
    expect(guarded).toMatch(
      /html\[data-theme="dark"\] \[data-site-header\] \.wordmark-light[\s\S]*?display:\s*none;/,
    );
    expect(guarded).toMatch(
      /html\[data-theme="dark"\] \[data-site-header\] \.wordmark-dark[\s\S]*?display:\s*block;/,
    );
    // No other dark-tone swap hooks (forced-colours dark themes pick by colour scheme).
    const elsewhere = css.replace(guarded, "");
    expect(elsewhere).not.toMatch(/\[data-tone="dark"\] \.wordmark-(light|dark)/);
  });

  // Generated by /ship coverage audit
  // Value: protects=under a dark forced-colours theme (Canvas near-black) the header and footer show the reversed lockup, since forced colours never recolour the image and the dark-ink logo would vanish;
  //   fails_when=the forced-colors dark block is deleted, loses its prefers-color-scheme dark condition, or stops swapping both colourways inside the header or the footer;
  //   why_new=the swap test above only proves the screen tone rules stay out of forced colours, not that dark forced colours get the reversed logo; seam=none
  it("shows the reversed header and footer lockups under a dark forced-colours theme", () => {
    const css = readFileSync(path.resolve(__dirname, "../../../src/app/globals.css"), "utf8");
    const dark = cssBlockAfter(
      css,
      "@media (forced-colors: active) and (prefers-color-scheme: dark)",
    );
    const scope = String.raw`:is\(\[data-site-header\], \[data-site-footer\]\)`;
    expect(dark).toMatch(new RegExp(`${scope} \\.wordmark-light\\s*\\{\\s*display:\\s*none;`));
    expect(dark).toMatch(new RegExp(`${scope} \\.wordmark-dark\\s*\\{\\s*display:\\s*block;`));
  });
});
