import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { blend, contrastRatio, parseCssVars } from "@/lib/a11y/contrast";

const TOKENS = path.resolve(__dirname, "../../src/styles/tokens");
// Read from the button itself so raising `hover:brightness-*` there cannot outrun this check.
const HOVER_BRIGHTNESS =
  Number(
    /hover:brightness-(\d+)/.exec(
      readFileSync(path.resolve(__dirname, "../../src/components/ui/button.tsx"), "utf8"),
    )?.[1],
  ) / 100;
const WCAG_AA_TEXT = 4.5;

// What `filter: brightness(1.1)` does to a #rrggbb colour (each channel scaled and clamped).
const brightened = (hex: string): string =>
  `#${[1, 3, 5]
    .map((i) =>
      Math.min(255, Math.round(parseInt(hex.slice(i, i + 2), 16) * HOVER_BRIGHTNESS))
        .toString(16)
        .padStart(2, "0"),
    )
    .join("")}`;

describe("primary button gradient", () => {
  // Value: protects=the primary button label stays readable over every stop of the brand gradient, also at hover brightness; fails_when=a gradient stop is lightened or the label colour changes so any stop drops below 4.5:1; why_new=contrast-pairs.json only tests solid pairs, so a gradient end stop at 2.96:1 shipped unnoticed; seam=none
  it("keeps the label at 4.5:1 or better on every stop, resting and hovered", () => {
    const vars = parseCssVars(readFileSync(path.join(TOKENS, "color.css"), "utf8"));
    const label = vars["--color-prominent-fg"]!;
    const gradient = /--background-image-brand:\s*linear-gradient\(([^;]+)\);/.exec(
      readFileSync(path.join(TOKENS, "ecosystem.css"), "utf8"),
    );
    const stops = [...(gradient?.[1] ?? "").matchAll(/#[0-9a-f]{6}/gi)].map((m) => m[0]);
    expect(stops.length).toBeGreaterThanOrEqual(3);
    for (const stop of stops) {
      expect(contrastRatio(label, stop), `${stop} resting`).toBeGreaterThanOrEqual(WCAG_AA_TEXT);
      expect(
        contrastRatio(brightened(label), brightened(stop)),
        `${stop} hovered`,
      ).toBeGreaterThanOrEqual(WCAG_AA_TEXT);
    }
  });
});

describe("glass control rim", () => {
  const globals = readFileSync(path.resolve(__dirname, "../../src/app/globals.css"), "utf8");
  const vars = parseCssVars(readFileSync(path.join(TOKENS, "color.css"), "utf8"));
  const NON_TEXT = 3;
  const rimToken = (selector: RegExp): string => {
    const token = new RegExp(
      `${selector.source}\\s*\\{[^}]*?border-color:\\s*var\\((--[\\w-]+)\\);`,
    ).exec(globals)?.[1];
    expect(token, selector.source).toBeDefined();
    return token!;
  };

  // Generated by /ship coverage audit
  // Value: protects=secondary (glass) buttons draw a rim that reads as a control boundary at 3:1 (WCAG 1.4.11) on paper and on dark plates and the dark-toned header, and increased contrast swaps every glass rim, plate and dark header included, to full ink;
  //   fails_when=the rim goes back to a soft fg mix, the plate/dark-header rule loses either selector or its strong token, a token is lightened below 3:1, or the prefers-contrast list drops the plate or dark-header variants they would otherwise outrank;
  //   why_new=button.test only checks the glass-control class name and contrast-pairs.json checks tokens without knowing which ones the rim uses; seam=none
  it("keeps the rim at 3:1 on light grounds, plates and the dark header", () => {
    const light = rimToken(/\n {2}\.glass-control/);
    for (const ground of ["--color-bg", "--color-bg-elevated"]) {
      expect(
        contrastRatio(vars[light]!, vars[ground]!),
        `${light} on ${ground}`,
      ).toBeGreaterThanOrEqual(NON_TEXT);
    }
    const dark = rimToken(
      /\.plate-surface \.glass-control,\s*\[data-site-header\]\[data-tone="dark"\] \.glass-control/,
    );
    for (const ground of ["--color-plate", "--color-plate-elevated"]) {
      expect(
        contrastRatio(vars[dark]!, vars[ground]!),
        `${dark} on ${ground}`,
      ).toBeGreaterThanOrEqual(NON_TEXT);
    }

    const at = globals.indexOf("@media (prefers-contrast: more) {\n    .glass,");
    expect(at).toBeGreaterThanOrEqual(0);
    const rule = globals.slice(at, globals.indexOf("}", at));
    expect(rule).toContain(".plate-surface :is(.glass, .glass-control, .surface-material)");
    expect(rule).toContain('[data-site-header][data-tone="dark"] :is(.glass, .glass-control)');
    expect(rule).toMatch(/border-color:\s*var\(--color-fg\);/);
  });

  // Generated by /ship pre-landing review
  // Value: protects=hovering a glass control firms its rim toward the label ink (not only the near-invisible fill step), controls inside the header capsule drop their own floating shadow (no glass on glass), and plate cards keep their specular rim on hover;
  //   fails_when=the hover rim rule is removed or leaks into increased contrast, the header control rule regains a drop shadow, or hover-lift's ink shadow again replaces the plate card's inset highlight;
  //   why_new=the design review found the hover state reading only as scale, a doubled glass layer in the header, and the plate highlight vanishing on hover; seam=none
  it("firms the rim on hover, keeps header controls flat and plate cards lit", () => {
    const hover = globals.slice(
      globals.indexOf("@media (prefers-contrast: no-preference) {\n    .glass-control:hover"),
    );
    expect(hover.slice(0, hover.indexOf("}"))).toMatch(
      /border-color:\s*color-mix\(in srgb, var\(--color-fg\) 60%, transparent\);/,
    );
    const shadowOf = (selector: string): string => {
      const at = globals.indexOf(`${selector} {`);
      expect(at, selector).toBeGreaterThanOrEqual(0);
      return globals.slice(at, globals.indexOf("}", at));
    };
    for (const selector of [
      "[data-site-header] .glass .glass-control",
      '[data-site-header][data-tone="dark"] .glass .glass-control',
    ]) {
      const rule = shadowOf(selector);
      expect(rule, selector).toMatch(/box-shadow:\s*inset 0 1px 0 rgb\(255 255 255 \/ 0\.\d+\);/);
    }
    const plate = shadowOf(
      ".plate-surface .surface-material.hover-lift:hover,\n  .plate-surface .surface-material.hover-lift:focus-visible",
    );
    expect(plate).toMatch(/inset 0 1px 0 rgb\(255 255 255 \/ 0\.12\)/);
  });
});

describe("header call to action ring", () => {
  const globals = readFileSync(path.resolve(__dirname, "../../src/app/globals.css"), "utf8");
  const seconds = (value: string) =>
    value.endsWith("ms") ? Number.parseFloat(value) / 1000 : Number.parseFloat(value);

  // Generated by /ship follow-up (header CTA)
  // Value: protects=the Demo ring's arrival animation stops within five seconds (no pause control needed, WCAG 2.2.2), runs only without reduced motion, and increased contrast swaps it for a solid ink rim;
  //   fails_when=the orbit is made infinite or longer than 5s, the animation escapes the reduced-motion guard, or the prefers-contrast fallback is dropped;
  //   why_new=the ring is new; a looping attention animation would breach 2.2.2 silently; seam=none
  it("orbits for under five seconds, only with motion allowed, and goes solid for increased contrast", () => {
    const motion = globals.indexOf(
      "@media (prefers-reduced-motion: no-preference) {\n    .cta-attention {",
    );
    expect(motion).toBeGreaterThanOrEqual(0);
    const block = globals.slice(motion, globals.indexOf("}", motion));
    const runs = [...block.matchAll(/cta-[a-z]+ ([\d.]+m?s) [^,;]*? (\d+)[,;]/g)];
    expect(runs.length).toBeGreaterThan(0);
    for (const [, duration, count] of runs) {
      expect(seconds(duration!) * Number(count)).toBeLessThan(5);
    }
    expect(globals).not.toMatch(/cta-[a-z]+[^;]*infinite/);
    const before = globals.slice(0, motion);
    expect(before.slice(before.lastIndexOf(".cta-attention {"))).not.toMatch(/animation:/);
    const contrast = globals.indexOf("@media (prefers-contrast: more) {\n    .cta-attention {");
    expect(globals.slice(contrast, globals.indexOf("}", contrast))).toMatch(
      /border-color:\s*var\(--color-fg\);/,
    );
  });
});

describe("contrastRatio", () => {
  it("returns 21 for black on white", () => {
    expect(contrastRatio("#000000", "#ffffff")).toBeCloseTo(21, 1);
  });
  it("returns 1 for identical colours", () => {
    expect(contrastRatio("#336699", "#336699")).toBeCloseTo(1, 3);
  });
  it("parses 3- and 6-digit hex custom properties", () => {
    expect(parseCssVars(":root{--a:#fff;--b: #123456 ;}")).toEqual({
      "--a": "#fff",
      "--b": "#123456",
    });
  });
});

describe("blend", () => {
  // Generated by /ship coverage audit
  // Value: protects=the header-glass and hero-scrim contrast bounds are computed from the real composite of a translucent layer over its backdrop;
  //   fails_when=blend reads the wrong channel offsets (the hero-stage helper it replaced sliced "#rrggbb" at 1,3,5, which is off by one once expandHex strips the "#"), swaps top and below, inverts alpha, or mis-expands 3-digit tokens;
  //   why_new=blend is new and only reached through two threshold assertions that can still pass on a wrong colour; seam=none
  it("composites the top colour at alpha over the opaque one below, per channel", () => {
    expect(blend("#336699", 1, "#000000")).toBe("#336699");
    expect(blend("#336699", 0, "#ffffff")).toBe("#ffffff");
    expect(blend("#ffffff", 0.5, "#000000")).toBe("#808080");
    expect(blend("#ff0000", 0.25, "#0000ff")).toBe("#4000bf");
    expect(blend("#fff", 0.75, "#000")).toBe("#bfbfbf");
  });
});
